DROP VIEW [dds_esquema].[Promedio Ultimo Partido]
DROP VIEW [dds_esquema].[Promedio todos los partidos]
drop table [dds_esquema].[CalificacionPendiente]
drop table [dds_esquema].[Calificacion]
drop table [dds_esquema].[Infraccion]
drop TABLE [dds_esquema].[JugadorAmigo]
drop TABLE [dds_esquema].[Rechazo]
drop TABLE [dds_esquema].[InscripcionPendiente]
drop TABLE [dds_esquema].[PartidoEquipo]
drop TABLE [dds_esquema].[Inscripcion]
drop TABLE [dds_esquema].[Partido]
drop TABLE [dds_esquema].[Jugador]
drop TABLE [dds_esquema].[Administrador]
drop SCHEMA [dds_esquema]